### PR TITLE
Remove UN_APP reference in config docs

### PR DESCRIPTION
**Pull request by siwyd**
The docs seem to indicate this environmental variable would be present, but it's not, which is a bit confusing.

### CODE REVIEW

**Comment by davidnewhall** [comment]
I'd rather fix the bug than make the documentation incorrect too.

**Comment by siwyd** [comment]
@davidnewhall Ah, I just assumed it was a historic leftover perhaps. So this env variable really is supposed to be there then?

**Comment by davidnewhall** [comment]
This should be fixed in Unpackerr 0.13.1. Lemme know.

**Comment by siwyd** [comment]
@davidnewhall Awesome, thank you. I can confirm I can see the UN_APP variable is set if I dump env!

**Pull request closed without merging**
